name: CI Workflow that runs hadolint and shellcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: .devcontainer/Dockerfile.base
        ignore: DL3008,SC2046,SC2016
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: .devcontainer/Dockerfile.full
        ignore: DL3008,SC2046,SC2016

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2016 -e SC1091 -e SC2181 -e SC2086 -e SC1090